name: seedlyDeployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PEM_KEY }}

          script: |
            cd /home/ubuntu/seedly
            npm install
            npm run build
            pm2 restart Frontend || pm2 start npm --name "Frontend" -- run start
